### ISSUE TITLE
Broken deployment?

### ISSUE THREAD

**Issue by dburles** [alanhkarp/SitePasswordWeb#3]
Seems to be broken at https://sitepassword.info/ with the following error in the console: `Uncaught TypeError: SitePassword.xorStrings is not a function`

However, the version at https://alanhkarp.github.io/SitePasswordWeb/ is working.

**Comment by alanhkarp** [comment]
Fixed.  I had forgotten to apply the update.

**Comment by alanhkarp** [comment]
@dburles Thanks for reporting the bug.  I'd like to learn more about your interest in SitePassword.  Please contact me at alanhkarp@gmail.com.
